accelerator: gpu
accumulate_grad_batches: null
amp_backend: native
amp_level: null
apply_s2: false
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 349
benchmark: null
check_val_every_n_epoch: 1
dataset: different_hods
default_root_dir: null
detect_anomaly: false
deterministic: null
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
ipus: null
learning_rate: 0.022132407905402808
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
logger: true
loss: mae
max_epochs: null
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
model_dir: ../../trained_models
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_hidden: 89
n_input: 15
n_layers: 6
n_output: 74
normalize: true
normalize_inputs: true
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
overfit_batches: 0.0
plugins: null
precision: 32
profiler: null
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
run_name: optuna_ds3_cross
s_max: null
s_min: null
standarize: false
statistic: ds3_cross
strategy: null
sync_batchnorm: false
tpu_cores: null
track_grad_norm: -1
val_check_interval: null
weight_decay: 0.003107085975531378
weights_save_path: null
