
slice_filters:
    s: [0.7,150.]

select_filters:
    quintiles: [0,1,3,4,]
    multipoles: [0,2]

statistics: ['tpcf', 'density_split_cross', 'density_split_auto']
data:
    observation: 
        class: 'Abacus'
        args:
            dataset: 'bossprior'
        get_obs_args:
            cosmology: 0  
            hod_idx: 26 
    covariance:
        class: 'AbacusSmall'
        dataset: 'bossprior'
        add_emulator_error_test_set: true 
        add_simulation_error: true
        add_predicted_uncertainty: false 
        volume_scaling: 64.0

fixed_parameters: [] #'w0_fld', 'wa_fld', 'nrun', 'N_ur'] 

theory_model:
    module: 'sunbird.summaries'
    class: 'Bundle'
    args:
        dataset: 'bossprior'
        loss: 'learned_gaussian'
        flax: True

inference:
    output_dir: '/n/home11/ccuestalazaro/sunbird/scripts/inference/chains/ds_tpcf_hmc_gauss'

priors:
    stats_module: 'numpyro.distributions'
    omega_b:
        distribution: 'Uniform'
        low: 0.0207
        high: 0.0243
    
    omega_cdm:
        distribution: 'Uniform'
        low: 0.1032
        high: 0.140

    sigma8_m:
        distribution: 'Uniform'
        low: 0.678
        high: 0.938
    n_s:
        distribution: 'Uniform'
        low: 0.9012
        high: 1.025
    nrun:
        distribution: 'Uniform'
        low: -0.038
        high: 0.038

    N_ur:
        distribution: 'Uniform'
        low: 1.188
        high: 2.889

    w0_fld:
        distribution: 'Uniform'
        low: -1.22
        high: -0.726

    wa_fld:
        distribution: 'Uniform'
        low: -0.628
        high: 0.621

    logM1:
        distribution: 'Uniform'
        low: 13.2
        high: 14.4

    logM_cut:
        distribution: 'Uniform'
        low: 12.4
        high: 13.3
    alpha:
        distribution: 'Uniform'
        low: 0.7
        high: 1.5
    alpha_s:
        distribution: 'Uniform'
        low: 0.7
        high: 1.3
    alpha_c:
        distribution: 'Uniform'
        low: 0.
        high: 0.5
    logsigma:
        distribution: 'Uniform'
        low: -3.
        high: 0
    kappa:
        distribution: 'Uniform'
        low: 0.
        high: 1.5
    B_cen:
        distribution: 'Uniform'
        low: -0.5
        high: 0.5

    B_sat:
        distribution: 'Uniform'
        low: -1.
        high: 1.