data:
  path_to_observation: '/n/home11/ccuestalazaro/sunbird/data/inference/multipoles_c0_hod60.npy'
  path_to_covariance_data: '/n/home11/ccuestalazaro/sunbird/data/full_ap/covariance/ds_cross_xi_smu_zsplit_Rs20_landyszalay_randomsX50.npy'
  path_to_fixed_parameters: '/n/home11/ccuestalazaro/sunbird/data/inference/cosmology_c140_hod60.json'
  quintiles: [0,1,3,4]
  s_min: 30.
  fixed_parameters: [
    'omega_b', 'omega_cdm', 'sigma8_m', 'n_s', 'nrun', 'N_ur', 'w0_fld', 'wa_fld', 
    #'logM1', 'logM_cut', 'alpha', 'alpha_sat', 'alpha_c', 
    #'sigma', 'kappa'
]

theory_model:
    module: 'sunbird.models.density_split'
    class: 'DensitySplit'
    params: 
        path_to_models: '/n/home11/ccuestalazaro/sunbird/trained_models/'
inference:
    output_dir: '/n/home11/ccuestalazaro/sunbird/scripts/inference/results_dynasty_c140/'

priors:
    stats_module: 'scipy.stats'
    omega_b:
        distribution: 'uniform'
        min: 0.0209
        max: 0.0243

    omega_cdm:
        distribution: 'uniform'
        min: 0.1032
        max: 0.140

    sigma8_m:
        distribution: 'uniform'
        min: 0.678
        max: 0.938
    n_s:
        distribution: 'uniform'
        min: 0.9012
        max: 1.025
    nrun:
        distribution: 'uniform'
        min: -0.038
        max: 0.038

    N_ur:
        distribution: 'uniform'
        min: 1.188
        max: 2.889

    w0_fld:
        distribution: 'uniform'
        min: -1.22
        max: -0.726

    wa_fld:
        distribution: 'uniform'
        min: -0.628
        max: 0.621

    logM1:
        distribution: 'uniform'
        min: 13.2
        max: 14.4

    logM_cut:
        distribution: 'uniform'
        min: 12.4
        max: 13.3

    alpha:
        distribution: 'uniform'
        min: 0.7
        max: 1.49

    alpha_sat:
        distribution: 'uniform'
        min: 0.7
        max: 1.29

    alpha_c:
        distribution: 'uniform'
        min: 0.
        max: 0.5

    sigma:
        distribution: 'loguniform'
        a: 0.001
        b: 1.

    kappa:
        distribution: 'uniform'
        min: 0.
        max: 1.49


