slice_filters:
    s: [0.7, 151.]

select_filters:
    multipoles: [0, 1]

data:
    cosmology: 13
    hod_idx: 0
    summaries: ['tpcf']

fixed_parameters: ['alpha_c', 'alpha_s'] #'w0_fld', 'wa_fld',]

theory_model:
    module: 'sunbird.summaries'
    class: 'TPCF'

inference:
    output_dir: 'dynesty_results/'

priors:
    stats_module: 'scipy.stats'
    omega_b:
        distribution: 'norm'
        mean: 0.02268
        dispersion: 0.00038
    omega_cdm:
        distribution: 'uniform'
        min: 0.1032
        max: 0.140

    sigma8_m:
        distribution: 'uniform'
        min: 0.678
        max: 0.938
    n_s:
        distribution: 'uniform'
        min: 0.9012
        max: 1.025
    nrun:
        distribution: 'uniform'
        min: -0.038
        max: 0.038

    N_ur:
        distribution: 'uniform'
        min: 1.188
        max: 2.889

    w0_fld:
        distribution: 'uniform'
        min: -1.22
        max: -0.726

    wa_fld:
        distribution: 'uniform'
        min: -0.628
        max: 0.621

    logM1:
        distribution: 'uniform'
        min: 13.2
        max: 14.4

    logM_cut:
        distribution: 'uniform'
        min: 12.4
        max: 13.3

    alpha:
        distribution: 'uniform'
        min: 0.7
        max: 1.49

    alpha_s:
        distribution: 'uniform'
        min: 0.7
        max: 1.29

    alpha_c:
        distribution: 'uniform'
        min: 0.
        max: 0.5

    sigma:
        distribution: 'uniform'
        min: 0.001
        max: 1
    kappa:
        distribution: 'uniform'
        min: 0.
        max: 1.49


